version: '3'
services:
  mysqldb:
    image: mysql:latest
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: smart_cafe
  smart-cafe:
    build: .
    ports:
      - '8080:8080'
    depends_on:
      - mysqldb
